export const HOSPITAL_GET_REQUEST = 'HOSPITAL_GET_REQUEST';
export const HOSPITAL_GET_SUCCESS = 'HOSPITAL_GET_SUCCESS';
export const HOSPITAL_GET_FAIL = 'HOSPITAL_GET_FAIL';
export const HOSPITAL_GET_RESET = 'HOSPITAL_GET_RESET';

export const ROOM_BOOK_REQUEST = 'ROOM_BOOK_REQUEST';
export const ROOM_BOOK_SUCCESS = 'ROOM_BOOK_SUCCESS';
export const ROOM_BOOK_FAIL = 'ROOM_BOOK_FAIL';

export const BOOKING_GET_REQUEST = 'BOOKING_GET_REQUEST';
export const BOOKING_GET_SUCCESS = 'BOOKING_GET_SUCCESS';
export const BOOKING_GET_FAIL = 'BOOKING_GET_FAIL';
export const BOOKING_GET_RESET = 'BOOKING_GET_RESET';

export const BOOKING_DELETE_REQUEST = 'BOOKING_DELETE_REQUEST';
export const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS';
export const BOOKING_DELETE_FAIL = 'BOOKING_DELETE_FAIL';
